// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	DeleteCategory(ctx context.Context, categoryID int32) error
	FindAllCategory(ctx context.Context) ([]*Category, error)
	FindCategoryById(ctx context.Context, categoryID int32) (*Category, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
}

var _ Querier = (*Queries)(nil)
